apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: aperence/phoenix
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          # Variables to connect to our Postgres server.
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            value: postgres
          - name: PGDATABASE
            value: server_dev
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: postgres
          - name: ERLANG_COOKIE
            value: "secret"
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 4000
        command: ["elixir"]
        args: [
          "--name", 
          "server@$(MY_POD_IP)", 
          "--cookie","$(ERLANG_COOKIE)", 
          "--no-halt", 
          "-S","mix",
          "phx.server"
        ]
